var sogou_param = new Array();
sogou_param["pid"]  = 'wwwtu8com';
sogou_param["ct"]  = 'kwd';
sogou_param["fmt"]  = 'h_kwd';
sogou_param["dn"]  = '6';
sogou_param["iw"]   = '478';
sogou_param["ih"]   = '15';
sogou_param["fs"] = '12';
sogou_param["c_bo"] = 'FFFFFF';
sogou_param["c_bg"] = 'trans';
sogou_param["c_fg"] = 'ff0198';
sogou_param["tdw"] = '';
sogou_param["charset"] = 'gb2312';
document.writeln("<script language='JavaScript' type='text\/javascript' src='http:\/\/images.sohu.com\/cs\/jsfile\/js\/lu.js'><\/script>");
